title: Presenting Android
description: Presenter First for Android

url: http://fmedlin.github.io/presenting-android
baseurl: '/presenting-android'
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: fmedlin
   twitter: fmedlin
   email: fred@medl.in

#google_analytics: "UA-58263416-1"
